spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/mydatabase?auto"
    username: root
    password: Good36520@
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true